# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "03 05 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/JLSchaap/nl-ngr-validation/tree/gh-pages
          path: def
         
       
      - name: Build with Maven
        run: mvn --file pom.xml test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/surefire-reports
